"""Fitting TALENT_CV -- how wrong the market is about a player's season.

`hub/draft/season.py` carried `TALENT_CV = 0.35` with a comment calling it "the single most
important number in the model" and admitting it had not been fitted. `docs/six-of-twelve.md`
then made it load-bearing: the season-long variance sweep that produced the corrected
draft-time advice is a sweep in exactly this quantity.

The instrument is the league's own past drafts. A draft pick is market opinion recorded
before week 1, so it cannot be contaminated by the season it is predicting -- unlike a
stored projection, which may have been revised after the fact. E[realized points | pick,
position] is therefore the market's projection, and the dispersion around it is the
quantity wanted.

Two corrections the naive version gets wrong, both pinned below:

- **Weekly sampling noise is not talent.** A season average over ~15 games carries its own
  spread, and counting it as talent dispersion overstates the answer.
- **Players who vanish from the data are the busts.** Retired players drop out of ESPN's
  universe, so an old season silently loses its worst outcomes and reads as more
  predictable than it was.
"""
import numpy as np
import polars as pl
import pytest

from hub.draft import calibrate


def _synthetic(cv_true, n=900, weekly_cv=0.55, weeks=17, seed=0, games=None):
    """Player-seasons generated by the model itself, so the fitted CV has a known answer."""
    rng = np.random.default_rng(seed)
    pick = rng.integers(1, 169, n)
    pos = rng.choice(["QB", "RB", "WR", "TE"], n)
    mu = 26.0 * pick ** -0.28                      # the market's projection, a power law
    true_mu = np.clip(mu * (1.0 + rng.normal(0.0, cv_true, n)), 0.0, None)
    g = np.full(n, weeks) if games is None else games
    total = np.array([rng.normal(true_mu[i] * g[i], weekly_cv * mu[i] * np.sqrt(max(g[i], 1)))
                      for i in range(n)])
    return pl.DataFrame({"season": [2024] * n, "pick": pick, "pos": pos,
                         "total": np.clip(total, 0.0, None), "games": g})


# --- the load-bearing test -------------------------------------------------

@pytest.mark.parametrize("cv_true", [0.20, 0.35, 0.50])
def test_it_recovers_a_cv_it_was_given(cv_true):
    """Generate from the model at a known CV, fit, get it back. Everything else here is a
    detail; if this fails the number is decoration."""
    got = calibrate.fit_talent_cv(_synthetic(cv_true))
    assert got["talent_cv"] == pytest.approx(cv_true, abs=0.03)


def test_weekly_noise_is_removed_rather_than_counted_as_talent():
    """At zero talent dispersion every player is exactly his projection plus weekly noise.
    A fitter that skipped the correction would report that noise as talent."""
    got = calibrate.fit_talent_cv(_synthetic(0.0))
    assert got["talent_cv"] < 0.08
    assert got["weekly"] > 0.10, "the noise it removed should be visible in the output"


def test_a_short_season_carries_more_sampling_noise_and_more_is_removed():
    """Eight games is twice the sampling variance of sixteen, so the correction has to
    scale with games played rather than being applied at some average rate. Same talent
    dispersion in both, so the same answer has to come out of both.

    The first version of this test varied games *randomly across players* and expected 0.35
    back; it got 0.45, and the test was wrong rather than the code. Realized scoring is
    measured per *team* game, so a player who misses half a season really did deliver half
    -- availability is deliberately inside the number, and random availability is real
    extra dispersion."""
    short = calibrate.fit_talent_cv(_synthetic(0.35, games=np.full(900, 8), seed=5))
    long_ = calibrate.fit_talent_cv(_synthetic(0.35, games=np.full(900, 16), seed=5))
    assert short["weekly"] > long_["weekly"], "a short season carries more sampling noise"
    assert short["talent_cv"] == pytest.approx(long_["talent_cv"], abs=0.05)
    assert long_["talent_cv"] == pytest.approx(0.35, abs=0.04)


# --- the corrections -------------------------------------------------------

def test_dropping_the_worst_outcomes_biases_the_answer_down():
    """Exactly what an old season does when its busts retire out of the player universe.
    This is why the headline fit excludes 2022."""
    df = _synthetic(0.45, n=1200)
    survivors = df.filter(pl.col("total") > pl.col("total").quantile(0.2))
    assert (calibrate.fit_talent_cv(survivors)["talent_cv"]
            < calibrate.fit_talent_cv(df)["talent_cv"] - 0.05)


def test_the_market_is_calibrated_to_be_unbiased_before_dispersion_is_measured():
    """If the fitted curve sat above or below the outcomes on average, that level error
    would be counted as spread."""
    got = calibrate.fit_talent_cv(_synthetic(0.35))
    assert got["mean_ratio"] == pytest.approx(1.0, abs=0.01)


def test_positions_are_fitted_separately_because_they_differ():
    got = calibrate.fit_talent_cv(_synthetic(0.35))
    assert set(got["by_position"]) == {"QB", "RB", "WR", "TE"}


def test_a_confidence_interval_comes_with_the_number():
    """A point estimate with no interval invites exactly the "it's 0.35" treatment this
    replaces."""
    got = calibrate.fit_talent_cv(_synthetic(0.35), bootstrap=300)
    lo, hi = got["ci95"]
    assert lo < got["talent_cv"] < hi
    assert hi - lo < 0.15


def test_players_who_never_played_are_kept():
    """A drafted player who tore an ACL in August is a real draft outcome and the worst
    one available. Dropping him is the survivorship bug in miniature."""
    df = _synthetic(0.35, n=400)
    hurt = pl.DataFrame({"season": [2024] * 20, "pick": list(range(1, 21)),
                         "pos": ["RB"] * 20, "total": [0.0] * 20, "games": [0] * 20})
    both = pl.concat([df, hurt])
    assert calibrate.fit_talent_cv(both)["n"] == both.height


# --- shape -----------------------------------------------------------------

def test_the_fit_reports_what_it_was_fitted_on():
    got = calibrate.fit_talent_cv(_synthetic(0.35))
    assert got["n"] == 900 and got["seasons"] == [2024]


def test_the_current_constant_is_inside_the_fitted_interval():
    """The guard. `TALENT_CV` was 0.35 on a guess and the fit put it 4.6 se too low; if
    somebody reverts it without re-fitting, this fails."""
    from hub.draft.season import TALENT_CV
    lo, hi = calibrate.FITTED_CI95
    assert lo <= TALENT_CV <= hi


# --- pulling the outcomes --------------------------------------------------

def _fetch(picks, players, season=2024):
    def fetch(yr, view="mTeam"):
        if view == "mDraftDetail":
            return {"draftDetail": {"picks": [{"playerId": p, "overallPickNumber": n}
                                              for p, n in picks]}}
        return {"players": [
            {"player": {"id": pid, "defaultPositionId": posid,
                        "stats": ([{"statSourceId": 0, "statSplitTypeId": 0,
                                    "seasonId": season, "appliedTotal": tot,
                                    "appliedAverage": avg}] if tot is not None else [])}}
            for pid, posid, tot, avg in players]}
    return fetch


def test_picks_are_matched_to_what_the_player_actually_scored():
    df = calibrate.draft_outcomes(
        [2024], fetch=_fetch([(11, 1), (22, 5)], [(11, 2, 170.0, 10.0), (22, 3, 96.0, 8.0)]))
    assert dict(zip(df["pick"].to_list(), df["total"].to_list())) == {1: 170.0, 5: 96.0}
    assert sorted(df["pos"].to_list()) == ["RB", "WR"]


def test_games_played_comes_from_total_over_average():
    """ESPN does not hand over a games count, and it is what the weekly-noise correction
    scales with, so getting it wrong would quietly mis-size the correction."""
    df = calibrate.draft_outcomes([2024], fetch=_fetch([(11, 1)], [(11, 2, 170.0, 17.0)]))
    assert df["games"][0] == 10


def test_undrafted_players_in_the_payload_are_ignored():
    """The request takes the top 800 by draft rank because filtering by id returns HTTP
    400. Most of what comes back was never drafted in this league."""
    df = calibrate.draft_outcomes(
        [2024], fetch=_fetch([(11, 1)], [(11, 2, 170.0, 10.0), (99, 3, 200.0, 12.0)]))
    assert df.height == 1


def test_a_player_with_no_recorded_actuals_is_skipped_not_zeroed():
    """Absent is not the same as zero. A missing stat line is ESPN losing the player, and
    scoring him zero would invent the worst possible outcome."""
    df = calibrate.draft_outcomes(
        [2024], fetch=_fetch([(11, 1), (22, 2)], [(11, 2, 170.0, 10.0), (22, 3, None, None)]))
    assert df.height == 1


def test_a_season_with_no_draft_is_an_error():
    with pytest.raises(ValueError):
        calibrate.draft_outcomes([2019], fetch=_fetch([], []))


def test_the_cli_prints_the_fit_against_the_value_in_use(capsys, monkeypatch):
    monkeypatch.setattr(calibrate, "draft_outcomes",
                        lambda seasons, fetch=None: _synthetic(0.41))
    assert calibrate.main(["--seasons", "2024"]) == 0
    out = capsys.readouterr().out
    assert "TALENT_CV" in out and "95% CI" in out and "in use" in out
    assert "RB" in out
